### ISSUE TITLE
RuntimeError: torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by ghd98522** [zyqz97/GP-NeRF#7]
When I was 95% trained, I reported this mistake, how to solve it?
![1692063980605](https://github.com/zyqz97/GP-NeRF/assets/141723481/054fa4f4-82dd-4a2c-ab53-a21e416d5097)

**Comment by zyqz97** [comment]
In this code, we set a "[--desired_chunks=60](https://github.com/zyqz97/GP-NeRF/blob/main/gp_nerf/opts.py#L50)" by default to save the space. This results in a limited amount of data in the chunk. The reason may be that data written in the chunk is used up when 94550 iters. A solution is to set "--desired_chunks=300" (which means write [all data](https://github.com/zyqz97/GP-NeRF/blob/main/gp_nerf/opts.py#L52) into the disk) if you have adequate disk space.

**Comment by ghd98522** [comment]
1. I see that this problem is due to the empty tensor passed in 130 lines torch.cat() in GP-nerf/mega-nerf/dataset/filesystem_dataset.py, I observe that the code here means to find a specific pixel of a specific image to select a specific sample point, why do you say that the amount of disk written is limited? I don't understand that.
2. Also, I see that this is in batch, so I solved this problem by increasing ray_chunk_size=10240, does this have an impact on the final training result? I trained PSNR only 19.6.
3. I am using my training model to verify, the result is wrong, how to solve this, the error message I put in the screenshot below.
I would appreciate it if you could help me answer these questions
![1692291200327](https://github.com/zyqz97/GP-NeRF/assets/141723481/e1e15957-09b7-41bc-8dfc-51b18716dc81)
![1692291261312](https://github.com/zyqz97/GP-NeRF/assets/141723481/acdcd398-bf4f-40f1-ab92-4d5ce9ed972b)

**Comment by zyqz97** [comment]
Thanks for your interest!
1.  We assign all training data into 300 chunks when using "--dataset_type=filesystem". But I only write 60 / 300 chunks because I have no enough space on the disk. You can see the size of chunks, only 60 of them have data and the rest of them are empty. So I said the written data is limited, and a solution is to set "--desired_chunks=300" to write all data.

2. I'm not sure what will happen when changing the "ray_chunk_size=10240". The results are normal according to my setting.

3. I guess it is caused by the different pillow versions.

![image](https://github.com/zyqz97/GP-NeRF/assets/48278265/c6cbccea-fd34-457b-bc60-6ce086aa52a5)

**Comment by ghd98522** [comment]
Very presumptuous to bother you again, I ran my own dataset with your project, it worked very badly, on the validation set psnr averaged only 13.9, I am curious what caused my results to be so poor, can you help take a look? The following four figures are the parameter settings, default, foreground, background, and prediction pictures.
![config](https://github.com/zyqz97/GP-NeRF/assets/141723481/07b5e57f-883d-4c68-941f-f3d567c6fc71)
![fg](https://github.com/zyqz97/GP-NeRF/assets/141723481/47f721b2-2312-430d-ae5d-22a376806a03)
![bg](https://github.com/zyqz97/GP-NeRF/assets/141723481/37061b51-d432-40fb-8120-3207a0de2dfe)
![pred](https://github.com/zyqz97/GP-NeRF/assets/141723481/3b324b4e-8c8a-4a90-aea8-1746800c3010)

**Comment by zyqz97** [comment]
It seems the results mostly came from the background model (the background model usually outputs the marginal area of the scene rather than the center area). You can check whether the ray_altitude is right or visualize the ellipsoid/sphere bound and your sample point to make sure most sample points are in the bound. Another way is ["--no_ellipse_bounds"](https://github.com/zyqz97/GP-NeRF/blob/main/gp_nerf/opts.py#L104), and you should normalize the camera position first. Thanks.

**Comment by ghd98522** [comment]
> It seems the results mostly came from the background model (the background model usually outputs the marginal area of the scene rather than the center area). You can check whether the ray_altitude is right or visualize the ellipsoid/sphere bound and your sample point to make sure most sample points are in the bound. Another way is ["--no_ellipse_bounds"](https://github.com/zyqz97/GP-NeRF/blob/main/gp_nerf/opts.py#L104), and you should normalize the camera position first. Thanks.

您好，还是之前那个问题，我的用GP-nerf跑的效果很差一直解决不掉这个问题，您在上个回复中说到可视化椭球体/球体边界和采样点的方法来确定ray_altitude，这个具体怎么做呀，再次感谢您！！！

**Comment by zyqz97** [comment]
> > It seems the results mostly came from the background model (the background model usually outputs the marginal area of the scene rather than the center area). You can check whether the ray_altitude is right or visualize the ellipsoid/sphere bound and your sample point to make sure most sample points are in the bound. Another way is ["--no_ellipse_bounds"](https://github.com/zyqz97/GP-NeRF/blob/main/gp_nerf/opts.py#L104), and you should normalize the camera position first. Thanks.
> 
> 您好，还是之前那个问题，我的用GP-nerf跑的效果很差一直解决不掉这个问题，您在上个回复中说到可视化椭球体/球体边界和采样点的方法来确定ray_altitude，这个具体怎么做呀，再次感谢您！！！

你好，mega-nerf和gpnerf的相机位姿是经过归一化的，相机分布在yz平面，大概范围是[-1，1]。 
ray_altitude限制采样范围（约束x轴范围，x轴的物理意义是场景的高度）。  
如果椭圆采样行不通（大概率是高度设置的不对，可以看看这个[代码](https://github.com/zyqz97/GP-NeRF/blob/main/scripts/colmap_to_mega_nerf.py)），你还可以直接尝试用球体采样的策略（采样点分布在单位球体内）。
另外，建议可视化采样点和相机，确保是正确的。
